services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: todo_db
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=embraceInternship2026!
        ports:
            - "1433:1433"

    api:
        build: ./backend
        container_name: todo_api
        depends_on:
            - db
        ports:
            - "5000:8080"
        environment:
            - ConnectionStrings__DefaultConnection=Server=db;Database=TodoDb;User Id=sa;Password=embraceInternship2026!;TrustServerCertificate=True;
