name: Azure Static Web Apps CI/CD (Frontend)

on:
    push:
        branches:
            - main
        paths:
            - "frontend/**" # Solo se dispara si hay cambios en la carpeta frontend
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main
        paths:
            - "frontend/**" # Solo se dispara para PRs que afecten al frontend

jobs:
    build_and_deploy_job:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        name: Build and Deploy Job
        steps:
            - uses: actions/checkout@v4 # Actualizado a v4
              with:
                  submodules: true
                  lfs: false

            - name: Build And Deploy
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_WAVE_04B7FB310 }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  action: "upload"

                  ###### Configuración del Monorepo ######
                  app_location: "/frontend" # Ruta raíz de tu Angular
                  api_location: "" # Vacío, tu API es externa (App Service)
                  output_location: "dist/todo-front/browser" # Ruta de salida de Angular 21
                  ###### Fin de la Configuración #######

    close_pull_request_job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_WAVE_04B7FB310 }}
                  action: "close"
